-- MySQL Script generated by MySQL Workbench
-- Seg 10 Abr 2017 05:52:19 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agendaonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agendaonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendaonline` DEFAULT CHARACTER SET utf8 ;
USE `agendaonline` ;

-- -----------------------------------------------------
-- Table `agendaonline`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaonline`.`plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `limit` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaonline`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaonline`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `plan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_plan1_idx` (`plan_id` ASC),
  CONSTRAINT `fk_user_plan1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `agendaonline`.`plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaonline`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaonline`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `email` VARCHAR(45) NULL,
  `number` VARCHAR(20) NULL,
  `born_day` INT NULL DEFAULT 0,
  `born_month` INT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_contact_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `agendaonline`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `agendaonline`.`plan` (`name`, `limit`) VALUES ('Gratuito', '20');
INSERT INTO `agendaonline`.`plan` (`name`, `limit`) VALUES ('Timido', '80');
INSERT INTO `agendaonline`.`plan` (`name`, `limit`) VALUES ('Ilimitado', '0');
